export const ADMIN_GET_ORDERS_REQUEST = 'ADMIN_GET_ORDERS_REQUEST'
export const ADMIN_GET_ORDERS_SUCCESS = 'ADMIN_GET_ORDERS_SUCCESS'
export const ADMIN_GET_ORDERS_FAIL = 'ADMIN_GET_ORDERS_FAIL'


export const ADMIN_SET_HOURS_REQUEST = 'ADMIN_SET_HOURS_REQUEST'
export const ADMIN_SET_HOURS_SUCCESS = 'ADMIN_SET_HOURS_SUCCESS'
export const ADMIN_SET_HOURS_FAIL = 'ADMIN_SET_HOURS_FAIL'