export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_BOOKING_REQUEST = 'USER_BOOKING_REQUEST'
export const USER_BOOKING_SUCCESS = 'USER_BOOKING_SUCCESS'
export const USER_BOOKING_FAIL = 'USER_BOOKING_FAIL'